# Generated by Django 5.2.17 on 2026-09-10 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_requests", "0001_initial"),
        ("tenants", "0005_scan_cooldown_en_minutes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accessrequest",
            name="unique_pending_access_request",
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Nouvelle"),
                    ("contacted", "Client contacté"),
                    ("proposal", "Proposition envoyée"),
                    ("granted", "Accordée"),
                    ("declined", "Refusée"),
                    ("cancelled", "Annulée par le client"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "contacted", "proposal"])
                ),
                fields=("tenant", "subject_type", "subject_key"),
                name="unique_open_access_request",
            ),
        ),
    ]
