# Generated by Django 5.2.16 on 2026-08-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreferences",
            name="weather_enrichment_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
