# Generated by Django 5.2.16 on 2026-08-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationpreferences_weather_enrichment_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("weather", "Météo cyber"),
                    ("realtime_alert", "Alerte temps réel"),
                    ("pre_incident", "Signal avant-coureur"),
                ],
                max_length=20,
            ),
        ),
    ]
