# Generated by Django 5.2.17 on 2026-09-15 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_pre_incident_email_kind"),
        ("tenants", "0005_scan_cooldown_en_minutes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("access_request_new", "Nouvelle demande d'un client"),
                            ("watched_account_declared", "Compte désigné déclaré"),
                            ("access_request_updated", "Suivi d'une demande"),
                            (
                                "watched_findings_new",
                                "Nouvelles fuites sur un compte surveillé",
                            ),
                            ("committee_report_ready", "Rapport de comité disponible"),
                            ("watch_update_published", "Publication de veille retenue"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("link", models.CharField(blank=True, max_length=200)),
                ("dedupe_key", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at"], name="notif_destinataire_lu"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dedupe_key", ""), _negated=True),
                        fields=("recipient", "dedupe_key"),
                        name="unique_notification_dedupe_par_destinataire",
                    )
                ],
            },
        ),
    ]
