# Generated by Django 5.2.17 on 2026-09-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_centre_de_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('access_request_new', "Nouvelle demande d'un client"), ('watched_account_declared', 'Compte désigné déclaré'), ('access_request_updated', "Suivi d'une demande"), ('watched_findings_new', 'Nouvelles fuites sur un compte surveillé'), ('committee_report_ready', 'Rapport de comité disponible'), ('watch_update_published', 'Publication de veille retenue'), ('training_campaign_done', 'Formation terminée par tous'), ('training_due_passed', 'Échéance de formation dépassée'), ('training_low_participation', 'Participation faible'), ('training_measure_suggested', 'Une formation peut renseigner le diagnostic')], max_length=40),
        ),
    ]
