# Generated by Django 5.2.16 on 2026-08-13 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_tenant_ai_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("subscription_activated", "Abonnement activé"),
                            ("subscription_suspended", "Abonnement suspendu"),
                            ("subscription_cancelled", "Abonnement résilié"),
                            ("plan_changed", "Offre modifiée"),
                            ("trial_started", "Essai ouvert"),
                            ("payment_recorded", "Paiement enregistré"),
                            ("plan_created", "Offre créée"),
                            ("plan_updated", "Offre mise à jour"),
                            ("plan_published", "Offre publiée"),
                            ("plan_retired", "Offre retirée"),
                            (
                                "demo_request_updated",
                                "Demande de démonstration traitée",
                            ),
                            ("tenant_created", "Entreprise créée"),
                        ],
                        max_length=40,
                    ),
                ),
                ("target", models.CharField(blank=True, max_length=200)),
                ("detail", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="platform_ad_created_57619f_idx"
                    ),
                    models.Index(
                        fields=["action"], name="platform_ad_action_1a0a34_idx"
                    ),
                ],
            },
        ),
    ]
