# Generated by Django 5.2.16 on 2026-08-14 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adminauditlog",
            name="changes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="adminauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("subscription_activated", "Abonnement activé"),
                    ("subscription_suspended", "Abonnement suspendu"),
                    ("subscription_cancelled", "Abonnement résilié"),
                    ("subscription_updated", "Abonnement modifié"),
                    ("plan_changed", "Offre modifiée"),
                    ("trial_started", "Essai ouvert"),
                    ("trial_extended", "Essai prolongé"),
                    ("quota_overridden", "Quota négocié appliqué"),
                    ("payment_recorded", "Paiement enregistré"),
                    ("plan_created", "Offre créée"),
                    ("plan_updated", "Offre mise à jour"),
                    ("plan_published", "Offre publiée"),
                    ("plan_retired", "Offre retirée"),
                    ("plan_duplicated", "Offre dupliquée"),
                    ("tenant_created", "Entreprise créée"),
                    ("tenant_updated", "Entreprise modifiée"),
                    ("tenant_archived", "Entreprise archivée"),
                    ("tenant_restored", "Entreprise restaurée"),
                    ("tenant_deleted", "Entreprise supprimée définitivement"),
                    ("user_invited", "Utilisateur invité"),
                    ("user_role_changed", "Rôle d'utilisateur modifié"),
                    ("user_deactivated", "Utilisateur désactivé"),
                    ("user_reactivated", "Utilisateur réactivé"),
                    ("user_removed", "Utilisateur retiré d'une entreprise"),
                    ("password_reset_sent", "Réinitialisation de mot de passe émise"),
                    ("monitored_asset_added", "Actif mis sous surveillance"),
                    ("monitored_asset_removed", "Actif retiré de la surveillance"),
                    ("scan_triggered", "Analyse déclenchée"),
                    ("secrets_purged", "Secrets purgés"),
                    ("demo_request_updated", "Demande de démonstration traitée"),
                    ("prospect_created", "Prospect créé"),
                    ("prospect_updated", "Prospect modifié"),
                    ("prospect_note_added", "Note ajoutée à un prospect"),
                    ("admin_invited", "Administrateur invité"),
                    ("admin_level_changed", "Niveau d'administrateur modifié"),
                    ("admin_revoked", "Administrateur retiré"),
                    ("setting_changed", "Réglage de plateforme modifié"),
                    ("export_generated", "Export généré"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="PlatformAdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("full", "Administrateur complet"),
                            ("commercial", "Commercial (lecture + prospects)"),
                        ],
                        default="commercial",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__email"],
            },
        ),
        migrations.CreateModel(
            name="PlatformSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=60, unique=True)),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
    ]
