# Generated by Django 5.2.17 on 2026-09-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "platform_admin",
            "0002_adminauditlog_changes_alter_adminauditlog_action_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("subscription_activated", "Abonnement activé"),
                    ("subscription_suspended", "Abonnement suspendu"),
                    ("subscription_cancelled", "Abonnement résilié"),
                    ("subscription_updated", "Abonnement modifié"),
                    ("plan_changed", "Offre modifiée"),
                    ("trial_started", "Essai ouvert"),
                    ("trial_extended", "Essai prolongé"),
                    ("quota_overridden", "Quota négocié appliqué"),
                    ("payment_recorded", "Paiement enregistré"),
                    ("plan_created", "Offre créée"),
                    ("plan_updated", "Offre mise à jour"),
                    ("plan_published", "Offre publiée"),
                    ("plan_retired", "Offre retirée"),
                    ("plan_duplicated", "Offre dupliquée"),
                    ("tenant_created", "Entreprise créée"),
                    ("tenant_updated", "Entreprise modifiée"),
                    ("tenant_archived", "Entreprise archivée"),
                    ("tenant_restored", "Entreprise restaurée"),
                    ("tenant_deleted", "Entreprise supprimée définitivement"),
                    ("user_invited", "Utilisateur invité"),
                    ("user_role_changed", "Rôle d'utilisateur modifié"),
                    ("user_deactivated", "Utilisateur désactivé"),
                    ("user_reactivated", "Utilisateur réactivé"),
                    ("user_removed", "Utilisateur retiré d'une entreprise"),
                    ("password_reset_sent", "Réinitialisation de mot de passe émise"),
                    ("monitored_asset_added", "Actif mis sous surveillance"),
                    ("monitored_asset_removed", "Actif retiré de la surveillance"),
                    ("scan_triggered", "Analyse déclenchée"),
                    ("secrets_purged", "Secrets purgés"),
                    ("referential_assigned", "Référentiel attribué"),
                    ("referential_revoked", "Référentiel retiré"),
                    ("access_request_handled", "Demande d'accès traitée"),
                    ("demo_request_updated", "Demande de démonstration traitée"),
                    ("prospect_created", "Prospect créé"),
                    ("prospect_updated", "Prospect modifié"),
                    ("prospect_note_added", "Note ajoutée à un prospect"),
                    ("admin_invited", "Administrateur invité"),
                    ("admin_level_changed", "Niveau d'administrateur modifié"),
                    ("admin_revoked", "Administrateur retiré"),
                    ("setting_changed", "Réglage de plateforme modifié"),
                    ("export_generated", "Export généré"),
                ],
                max_length=40,
            ),
        ),
    ]
