# Generated by Django 5.2.16 on 2026-08-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aijob",
            name="use_case",
            field=models.CharField(
                choices=[
                    ("document_charter", "Génération de charte informatique"),
                    ("assistant_reply", "Réponse de l'assistant"),
                    ("exposure_synthesis", "Synthèse d'exposition"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="aiusagelog",
            name="use_case",
            field=models.CharField(
                choices=[
                    ("document_charter", "Génération de charte informatique"),
                    ("assistant_reply", "Réponse de l'assistant"),
                    ("weather_enrichment", "Météo cyber enrichie"),
                    ("exposure_synthesis", "Synthèse d'exposition"),
                ],
                max_length=30,
            ),
        ),
    ]
