# Generated by Django 5.2.17 on 2026-09-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_exposure_synthesis"),
    ]

    operations = [
        migrations.AddField(
            model_name="generateddocument",
            name="source",
            field=models.CharField(
                choices=[
                    ("composed", "Composé à partir de vos données"),
                    ("ai", "Rédigé par l'IA, à relire"),
                ],
                default="ai",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="generateddocument",
            name="type",
            field=models.CharField(
                choices=[
                    ("security_policy", "Politique de sécurité du SI"),
                    ("it_charter", "Charte informatique"),
                    ("incident_procedure", "Procédure de gestion des incidents"),
                    ("incident_register", "Registre des incidents"),
                    ("continuity_plan", "Plan de continuité simplifié"),
                    ("awareness_sheet", "Fiche de sensibilisation"),
                    ("committee_report", "Rapport de comité de sécurité"),
                ],
                max_length=30,
            ),
        ),
    ]
