# Generated by Django 5.2.16 on 2026-08-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("down", "Site indisponible"),
                    ("ssl_expiring", "Certificat SSL bientôt expiré"),
                    ("security_headers", "En-têtes de sécurité manquants"),
                    ("email_misconfigured", "Configuration email incomplète"),
                    ("breach_compromise", "Compromission détectée"),
                ],
                max_length=30,
            ),
        ),
    ]
