# Generated by Django 5.2.17 on 2026-09-10 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessments", "0004_veille_reglementaire"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("publisher", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("feed_url", models.URLField(blank=True)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("rss", "Flux RSS"),
                            ("atom", "Flux Atom"),
                            ("page", "Page sans flux (détection de changement)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("expected_frequency", models.CharField(blank=True, max_length=120)),
                ("scope_note", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=0)),
                ("content_fingerprint", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["publisher", "name"],
            },
        ),
        migrations.CreateModel(
            name="WatchUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=1000)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("source_excerpt", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "À examiner"),
                            ("kept", "Retenue"),
                            ("integrated", "Intégrée au référentiel"),
                            ("dismissed", "Écartée"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("unqualified", "Non qualifiée"),
                            ("new_requirement", "Nouvelle exigence"),
                            ("update", "Évolution d'une exigence existante"),
                            (
                                "information",
                                "Information, sans effet sur un référentiel",
                            ),
                        ],
                        default="unqualified",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_summary_model", models.CharField(blank=True, max_length=60)),
                ("ai_summary_at", models.DateTimeField(blank=True, null=True)),
                ("ai_tokens_input", models.PositiveIntegerField(default=0)),
                ("ai_tokens_output", models.PositiveIntegerField(default=0)),
                (
                    "integrated_measures",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="assessments.measure"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="regulatory_watch.watchsource",
                    ),
                ),
                (
                    "target_referential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="assessments.referential",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-detected_at"],
                        name="regulatory__status_5f0328_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"),
                        name="unique_update_per_source",
                    )
                ],
            },
        ),
    ]
