# Generated by Django 5.2.17 on 2026-09-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_drop_extended_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="monthly_watched_account_scans",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plan",
            name="watched_accounts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="override_monthly_watched_account_scans",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="override_watched_accounts",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
