# Generated by Django 5.2.17 on 2026-09-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='access_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
