# Generated by Django 5.2.17 on 2026-09-21 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_scan_cooldown_en_minutes'),
        ('training', '0003_course_created_by_course_derived_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referential_slug', models.SlugField(max_length=220)),
                ('measure_code', models.CharField(max_length=50)),
                ('measure_title', models.CharField(max_length=300)),
                ('learners_total', models.PositiveIntegerField()),
                ('learners_done', models.PositiveIntegerField()),
                ('participation_rate', models.PositiveSmallIntegerField()),
                ('success_rate', models.PositiveSmallIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'À confirmer'), ('accepted', 'Confirmée'), ('dismissed', 'Écartée')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='training.course')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('tenant', 'course', 'measure_code'), name='unique_pending_measure_suggestion')],
            },
        ),
        migrations.CreateModel(
            name='NominativeAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='training.course')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='training_no_tenant__700db1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('mid', 'À mi-parcours'), ('before', "Avant l'échéance"), ('after', "Après l'échéance")], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='training.enrollment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'kind'), name='unique_reminder_per_kind')],
            },
        ),
        migrations.CreateModel(
            name='ReminderPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('mid_course', models.BooleanField(default=True)),
                ('before_due_days', models.PositiveSmallIntegerField(default=3)),
                ('after_due_days', models.PositiveSmallIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='unique_reminder_policy_per_tenant')],
            },
        ),
    ]
