# Generated by Django 5.2.17 on 2026-09-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_accessinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_profile",
            field=models.CharField(
                choices=[("executive", "Dirigeant"), ("technical", "Technique")],
                default="executive",
                max_length=12,
            ),
        ),
    ]
