# Generated by Django 5.2.17 on 2026-09-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profil_d_affichage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_dismissed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_result_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
