# Generated by Django 5.2.16 on 2026-08-07 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monitoring", "0002_alter_alert_alert_type"),
        ("tenants", "0002_tenant_ai_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BreachIntelligenceUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(blank=True, max_length=20)),
                ("requests_consumed", models.PositiveIntegerField(default=0)),
                ("remaining_after", models.IntegerField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("initial", "Scan initial (déclaration d'actif)"),
                            ("manual", "Scan manuel"),
                        ],
                        max_length=10,
                    ),
                ),
                ("findings_created", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BreachScanJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("running", "En cours"),
                            ("done", "Terminé"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("initial", "Scan initial (déclaration d'actif)"),
                            ("manual", "Scan manuel"),
                        ],
                        max_length=10,
                    ),
                ),
                ("result_ref", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breach_scan_jobs",
                        to="monitoring.asset",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BreachFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_endpoint",
                    models.CharField(
                        choices=[
                            ("stealer", "Logs de malware voleur d'identifiants"),
                            ("combo", "Liste combo (identifiant + mot de passe)"),
                            ("creds", "Identifiants exposés"),
                            ("sessions", "Sessions / cookies compromis"),
                            ("nhi", "Identité non-humaine (clé de service, token API)"),
                            ("darkweb", "Mention dark web"),
                            ("docs", "Document fuité"),
                            ("asm", "Surface d'attaque"),
                            ("radar", "Radar (mentions publiques)"),
                            ("webhook", "Notification temps réel (webhook)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("finding_type", models.CharField(max_length=60)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critique"),
                            ("high", "Élevée"),
                            ("attention", "Attention"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("treated", "Traité"),
                            ("ignored", "Ignoré"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("identifier_plain", models.CharField(blank=True, max_length=255)),
                ("identifier_masked", models.CharField(blank=True, max_length=255)),
                ("secret_masked", models.CharField(blank=True, max_length=32)),
                ("secret_seen", models.BooleanField(default=False)),
                ("breach_date", models.DateField(blank=True, null=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("dedup_hash", models.CharField(max_length=64)),
                ("treated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="monitoring.alert",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breach_findings",
                        to="monitoring.asset",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "treated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "-detected_at"],
                        name="threat_inte_tenant__510694_idx",
                    ),
                    models.Index(
                        fields=["asset", "-detected_at"],
                        name="threat_inte_asset_i_17cc80_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "dedup_hash"),
                        name="unique_breach_finding_per_tenant_dedup",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MonitoredAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="breachsense", max_length=30)),
                ("provider_ref", models.CharField(max_length=255)),
                (
                    "provider_asset_type",
                    models.CharField(default="domain", max_length=20),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_intel_monitored_asset",
                        to="monitoring.asset",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_ref"),
                        name="unique_provider_ref_per_provider",
                    )
                ],
            },
        ),
    ]
