# Generated by Django 5.2.16 on 2026-08-08 01:41
#
# ADR-014 (mise à jour) : remplace l'indicateur non réversible "un secret a
# été vu à l'ingestion" (secret_seen) par has_secret + secret_encrypted.
# Volontairement RemoveField + AddField, pas un RenameField : has_secret
# doit refléter "un blob chiffré est réellement disponible", pas hériter de
# la valeur de secret_seen des findings déjà en base (qui n'ont, eux, aucun
# secret chiffré à révéler) — les deux nouveaux champs prennent donc leur
# valeur par défaut (False / b"") pour toutes les lignes existantes.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_ai_enabled"),
        ("threat_intelligence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="breachfinding",
            name="secret_seen",
        ),
        migrations.AddField(
            model_name="breachfinding",
            name="has_secret",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="breachfinding",
            name="secret_encrypted",
            field=models.BinaryField(blank=True, default=b""),
        ),
        migrations.CreateModel(
            name="SecretRevealAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField()),
                (
                    "denial_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("role", "Rôle administrateur requis"),
                            ("step_up", "Ré-authentification invalide"),
                            ("no_secret", "Aucun secret chiffré disponible"),
                            (
                                "not_found",
                                "Fuite introuvable ou hors périmètre du tenant",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reveal_audits",
                        to="threat_intelligence.breachfinding",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="threat_inte_tenant__955e3a_idx",
                    )
                ],
            },
        ),
    ]
