# Generated by Django 5.2.16 on 2026-08-10 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_ai_enabled"),
        ("threat_intelligence", "0002_secret_reveal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExposureSynthesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("is_stale", models.BooleanField(default=False)),
                ("findings_fingerprint", models.CharField(blank=True, max_length=64)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant",), name="unique_exposure_synthesis_per_tenant"
                    )
                ],
            },
        ),
    ]
