# Generated by Django 5.2.16 on 2026-08-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threat_intelligence", "0003_exposure_synthesis"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretPurgeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("retention_days", models.PositiveIntegerField()),
                ("secrets_purged", models.PositiveIntegerField(default=0)),
                ("reveal_audits_deleted", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="breachfinding",
            name="secret_purged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
