# Generated by Django 5.2.17 on 2026-09-10 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_scan_cooldown_en_minutes"),
        ("threat_intelligence", "0008_adresses_en_clair"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="breachscanjob",
            name="scope",
            field=models.CharField(
                choices=[
                    ("assets", "Actifs déclarés"),
                    ("watched_accounts", "Comptes désignés"),
                ],
                default="assets",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WatchedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("executive", "Dirigeant ou mandataire social"),
                            ("employee", "Collaborateur"),
                            ("client", "Client ou partenaire"),
                            ("service", "Compte technique ou de service"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "legal_basis",
                    models.CharField(
                        choices=[
                            ("own", "C'est mon propre compte"),
                            (
                                "company",
                                "Compte professionnel fourni par mon entreprise",
                            ),
                            ("consent", "La personne concernée m'a donné son accord"),
                            (
                                "contract",
                                "Prévu au contrat qui me lie à cette personne",
                            ),
                            ("other", "Autre situation, que je précise ci-dessous"),
                        ],
                        max_length=20,
                    ),
                ),
                ("purpose", models.TextField()),
                ("declaration_text", models.TextField()),
                ("declaration_version", models.CharField(max_length=20)),
                ("declared_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("removal_reason", models.CharField(blank=True, max_length=200)),
                (
                    "declared_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-declared_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchedAccountFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_endpoint",
                    models.CharField(
                        choices=[
                            ("stealer", "Logs de malware voleur d'identifiants"),
                            ("combo", "Liste combo (identifiant + mot de passe)"),
                            ("creds", "Identifiants exposés"),
                            ("sessions", "Sessions / cookies compromis"),
                            ("nhi", "Identité non-humaine (clé de service, token API)"),
                            ("darkweb", "Mention dark web"),
                            ("docs", "Document fuité"),
                            ("asm", "Surface d'attaque"),
                            ("radar", "Radar (mentions publiques)"),
                            ("webhook", "Notification temps réel (webhook)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("finding_type", models.CharField(max_length=60)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critique"),
                            ("high", "Élevée"),
                            ("attention", "Attention"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("treated", "Traité"),
                            ("ignored", "Ignoré"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("identifier_masked", models.CharField(blank=True, max_length=255)),
                ("secret_masked", models.CharField(blank=True, max_length=32)),
                ("has_secret", models.BooleanField(default=False)),
                ("breach_date", models.DateField(blank=True, null=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("treated_at", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("dedup_hash", models.CharField(max_length=64)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="threat_intelligence.watchedaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="watchedaccount",
            index=models.Index(
                fields=["tenant", "is_active"], name="threat_inte_tenant__7e3007_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="watchedaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("tenant", "value"),
                name="unique_active_watched_account",
            ),
        ),
        migrations.AddIndex(
            model_name="watchedaccountfinding",
            index=models.Index(
                fields=["tenant", "status", "-detected_at"],
                name="threat_inte_tenant__c3a04a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="watchedaccountfinding",
            constraint=models.UniqueConstraint(
                fields=("tenant", "dedup_hash"), name="unique_watched_account_finding"
            ),
        ),
    ]
