"""Le premier passage, distingue des nouveautes (lot A).

Un premier scan remonte tout l'historique connu du fournisseur : mesure en
production, 3 222 entrees pour un seul compte. Les passages suivants ne
rapportent que du nouveau. Sans cette distinction, l'ecran presente une
reprise d'historique comme si tout etait arrive aujourd'hui, et le client
croit a une catastrophe.

Le remplissage des donnees existantes marque TOUTES les observations deja en
base comme venant du premier passage, et pose ``first_scanned_at`` a la plus
ancienne detection de chaque compte.

C'est exact et non une approximation : au moment ou cette migration est
ecrite, aucun compte surveille n'a ete analyse plus d'une fois — verifie en
production, une seule date d'analyse pour les 3 222 lignes. Presenter ces
lignes comme « apparues depuis » serait faux ; les presenter comme
l'historique qu'elles sont est ce que l'ecran doit dire.
"""

# Generated by Django 5.2.17 on 2026-09-11 21:30

from django.db import migrations, models


def marquer_l_historique(apps, schema_editor):
    """Tout ce qui est deja en base vient de la reprise d'historique."""
    WatchedAccount = apps.get_model("threat_intelligence", "WatchedAccount")
    WatchedAccountFinding = apps.get_model("threat_intelligence", "WatchedAccountFinding")

    WatchedAccountFinding.objects.update(from_first_scan=True)

    for compte in WatchedAccount.objects.all():
        premiere = (
            WatchedAccountFinding.objects.filter(account=compte)
            .order_by("detected_at")
            .values_list("detected_at", flat=True)
            .first()
        )
        if premiere is not None:
            compte.first_scanned_at = premiere
            compte.save(update_fields=["first_scanned_at"])


def defaire(apps, schema_editor):
    """Retour arriere : on ne detruit rien, on remet les valeurs par defaut."""
    apps.get_model("threat_intelligence", "WatchedAccountFinding").objects.update(
        from_first_scan=False
    )
    apps.get_model("threat_intelligence", "WatchedAccount").objects.update(first_scanned_at=None)


class Migration(migrations.Migration):
    dependencies = [
        ("threat_intelligence", "0009_comptes_designes"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchedaccount",
            name="first_scanned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="watchedaccountfinding",
            name="from_first_scan",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(marquer_l_historique, defaire),
    ]
