# Generated by Django 5.2.16 on 2026-08-04 19:59
#
# Replaces the product-invented "code" (e.g. "H1") with the ANSSI guide's
# actual numbering (1-42) — see docs/verification_referentiel_anssi.md.
# The one-off default=1 on the new unique `number` field only works
# against an empty `measure` table: fine for every real environment (CI's
# fresh test DB; any local/dev DB should be reset — no production data
# exists for this referential yet) but NOT retroactively safe once real
# data exists, at which point this would need a proper expand/contract
# migration instead.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measure",
            name="code",
        ),
        migrations.AddField(
            model_name="measure",
            name="effort_impact_disclaimer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="measure",
            name="number",
            field=models.PositiveSmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
