# Generated by Django 5.2.17 on 2026-09-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_referentiels_multiples"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="source_reference",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="measure",
            name="source_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
