# Generated by Django 5.2.16 on 2026-08-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="ai_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
