# Generated by Django 5.2.17 on 2026-09-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_account_manager_tenant_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="scan_cooldown_hours",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
