# Generated by Django 5.2.16 on 2026-08-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemoRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("company", models.CharField(max_length=160)),
                ("role", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(max_length=254)),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-9", "1 à 9 personnes"),
                            ("10-49", "10 à 49 personnes"),
                            ("50-249", "50 à 249 personnes"),
                            ("250+", "250 personnes et plus"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "preferred_slot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("morning", "Plutôt le matin"),
                            ("afternoon", "Plutôt l'après-midi"),
                            ("any", "Peu importe"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle"),
                            ("contacted", "Contactée"),
                            ("scheduled", "Démonstration planifiée"),
                            ("closed", "Close"),
                        ],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="marketing_d_status_438293_idx",
                    )
                ],
            },
        ),
    ]
