# Generated by Django 5.2.16 on 2026-08-14 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
        ("tenants", "0003_tenant_account_manager_tenant_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProspectNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="demorequest",
            name="converted_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="lost_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="next_follow_up_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Qui suit ce prospect.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="source",
            field=models.CharField(
                choices=[
                    ("public_form", "Formulaire du site"),
                    ("manual", "Saisie manuelle"),
                ],
                default="public_form",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="demorequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="demorequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Nouvelle"),
                    ("contacted", "Contactée"),
                    ("scheduled", "Démonstration planifiée"),
                    ("proposal", "Proposition envoyée"),
                    ("won", "Gagnée"),
                    ("lost", "Perdue"),
                    ("closed", "Close"),
                ],
                default="new",
                max_length=12,
            ),
        ),
        migrations.AddIndex(
            model_name="demorequest",
            index=models.Index(
                fields=["next_follow_up_on"], name="marketing_d_next_fo_961669_idx"
            ),
        ),
        migrations.AddField(
            model_name="prospectnote",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="prospectnote",
            name="demo_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="marketing.demorequest",
            ),
        ),
    ]
