# Generated by Django 5.2.16 on 2026-08-04 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actions", "0001_initial"),
        ("assessments", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actionitem",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_items",
                to="assessments.assessment",
            ),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="assessments.measure",
            ),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tenants.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="actionitem",
            constraint=models.UniqueConstraint(
                fields=("assessment", "measure"), name="unique_action_item_per_measure"
            ),
        ),
    ]
