# Generated by Django 5.2.17 on 2026-09-09 11:51

"""V2-3 — une echeance et une date de fin sur les actions (ADR-028).

« Actions en retard » etait demande au tableau de bord et ne pouvait pas
exister : sans echeance, rien n'est en retard. Et « actions terminees ce
trimestre » se serait appuye sur ``updated_at``, qui bouge a la moindre
correction de note.

Le remplissage approxime ``completed_at`` par ``updated_at`` pour les actions
DEJA faites. C'est une approximation, et elle est dite : la vraie date n'a
jamais ete enregistree, et la derniere modification d'une action terminee est
tres generalement celle qui l'a terminee. La seule alternative honnete serait
de laisser vide, ce qui ferait disparaitre du tableau de bord tout le travail
accompli avant cette version.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0002_initial"),
    ]

    def remplir(apps, schema_editor):
        ActionItem = apps.get_model("actions", "ActionItem")
        ActionItem.objects.filter(status="done", completed_at__isnull=True).update(
            completed_at=models.F("updated_at")
        )

    def vider(apps, schema_editor):
        """Rien a defaire : la colonne disparait avec le schema."""

    operations = [
        migrations.AddField(
            model_name="actionitem",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(remplir, vider),
    ]
